name = "vvip" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"

[[routes]]
pattern = "vvip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "ava.game.naver.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "graph.instagram.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "quiz.int.vidio.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "live.iflix.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "support.zoom.us.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "blog.webex.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "investors.spotify.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "cache.netflix.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "zaintest.vuclip.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "io.ruangguru.com.vip.bmkg.xyz"
custom_domain = true
[routes]]
pattern = "api.midtrans.com.vip.bmkg.xyz"
custom_domain = true

